name: Session Feed (Auto)

on:
  schedule:
    # GitHub Actions cron is in UTC.
    # 23:30 UTC (Mon-Fri) ~ 07:30 Manila (Asia session open)
    - cron: '30 23 * * 1-5'
    # 06:30 UTC (Mon-Fri) ~ 07:30 London (Europe session open during BST)
    - cron: '30 6 * * 1-5'
    # 12:30 UTC (Mon-Fri) ~ 08:30 New York (US session open during EDT)
    - cron: '30 12 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feed
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: |
          python scripts/generate_feed.py --sources config/sources.yml --out feed.xml

      - name: Commit & push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Auto: session feed update [skip ci]"
            git push
          fi
