name: Test Secret and Fetch EUR/USD Price

on:
  workflow_dispatch:

jobs:
  fetch-price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check API key and fetch price
        run: |
          if [ -z "${{ secrets.ALPHA_VANTAGE_API_KEY }}" ]; then
            echo "⚠️ Secret ALPHA_VANTAGE_API_KEY is empty or not found. Skipping fetch."
            exit 0
          fi

          echo "Fetching EUR/USD price..."
          RESPONSE=$(curl -s "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=EUR&to_currency=USD&apikey=${{ secrets.ALPHA_VANTAGE_API_KEY }}")
          echo "Raw API response:"
          echo "$RESPONSE"

          echo "Parsed rate:"
          echo "$RESPONSE" | jq -r '."Realtime Currency Exchange Rate"."5. Exchange Rate"'
