name: Test Alpha Vantage API

on:
  workflow_dispatch:   # run manually

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Alpha Vantage EUR/USD
        run: |
          echo "Fetching EUR/USD price..."
          curl -s "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=EUR&to_currency=USD&apikey=${{ secrets.ALPHAVANTAGE_API_KEY }}" | jq .

