- name: Fetch EUR/USD price
  run: |
    echo "Fetching EUR/USD price..."
    RESPONSE=$(curl -s "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=EUR&to_currency=USD&apikey=${{ secrets.ALPHA_VANTAGE_API_KEY }}")
    echo "Raw API response:"
    echo "$RESPONSE"
    echo "Parsed rate:"
    echo "$RESPONSE" | jq -r '."Realtime Currency Exchange Rate"."5. Exchange Rate"'
