name: Test Alpha Vantage Secret

on:
  workflow_dispatch:   # lets you run it manually

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check API key is available
        run: |
          echo "API key is set!"
          echo "First 5 chars: ${ALPHAVANTAGE_API_KEY:0:5}"
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
