name: Test Alpha Vantage Secret

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug API key present
        run: |
          if [ -z "${{ secrets.ALPHA_VANTAGE_API_KEY }}" ]; then
            echo "❌ Secret is empty or not found"
            exit 1
          else
            echo "✅ Secret is set (hidden for security)"
          fi

      - name: Fetch EUR/USD price
        run: |
          echo "Fetching EUR/USD price..."
          RESPONSE=$(curl -s "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=EUR&to_currency=USD&apikey=${{ secrets.ALPHA_VANTAGE_API_KEY }}")
          echo "Raw API response:"
          echo "$RESPONSE"
          echo "Parsed rate:"
          echo "$RESPONSE" | jq -r '."Realtime Currency Exchange Rate"."5. Exchange Rate"'

